### ISSUE TITLE
[BUG]: Refresh Token is ignored

### ISSUE THREAD

**Issue by kyoh86** [octokit/auth-oauth-device.js#163]
### What happened?

When I get the GitHub APP user authentication object having refresh-token and use it with `createOAuthDeviceAuth` strategy in Octokit Client, Octokit client never refreshes authentication.
From the looks of it, this library does not seem to handle Refresh Token properly.
I am trying to authenticate a user using Device Flow, which does not require a Client Secret, for a client-side product, but I am having to go through the authorization process again, even though the Refresh Token is still valid.

### Versions

Octokit v3.0.0 Deno v1.35.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
if you could provide a minimal test case to reproduce the problem, that'd be a great start to help identify the cause and fix it

**Comment by l1qu1d** [comment]
@kyoh86 from the sound of it, and without seeing your code, it seems like you're trying to use the `refreshToken` for authentication.  You refresh a `token`, (e.g. get a new `token`) using a `refreshToken` and use that _new_ `token` for authentication.

To do so, you must make a POST request to the `https://github.com/login/oauth/access_token` endpoint using the `refreshToken` to get a new `token` to use for authentication. Also note, that calling that endpoint you must also use a `client_secret`. If you can't include secrets in your app then you'll have to do a backend solution to call that endpoint.

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/refreshing-user-access-tokens

If you want to use the original `token` without expiration, the link above also includes how to opt-out your app. Then you don't have to worry about refreshing tokens.

I just had to go through the miles of documentation myself while building my extenstion app.
