### ISSUE TITLE
[FEAT]: Add CommonJS build output

### ISSUE THREAD

**Issue by marianheinsen** [octokit/auth-oauth-device.js#266]
### Describe the need

I'm using this library as a dependency in a project which unfortunately is forced to use CommonJS and can't migrate to ES Modules yet. This leads to issues, because this library doesn't output a CJS build as e.g. @octokit/rest.js so I'm forced to convert it to CJS using a bundler before using it. Please add this feature, it should only be a matter of updating the build.mjs script according to https://github.com/octokit/rest.js/blob/main/scripts/build.mjs#L44

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
> I'm using this library as a dependency in a project which unfortunately is forced to use CommonJS and can't migrate to ES Modules yet

that's okay, you can use the last `6.x` version. We will backport security fixes to `6.x` and other CommonJS version across the @octokit packages.
