### ISSUE TITLE
refresh_token

### ISSUE THREAD

**Issue by 89z** [octokit/auth-oauth-device.js#50]
From here:

https://github.com/octokit/auth-oauth-device.js/blob/08293d35357ff51839d8c2c044cf1864b843c75b/test/index.test.ts#L253-L260

it seems that its possible to get a `refresh_token`. However running a similar request returns something like this:

~~~json
{
 "access_token": "gho_16C7e42F292c6912E7710c838347Ae1...",
  "token_type": "bearer",
  "scope": "user"
}
~~~

where the `refresh_token` is missing. How do we get the `refresh_token`, or how long does the `access_token` last?

https://docs.github.com/developers/apps/building-oauth-apps/authorizing-oauth-apps

**Comment by gr2m** [comment]
`refresh_tokens` are not available to OAuth Apps, only to GitHub Apps, and only when enabled in the GitHub App's option:
https://docs.github.com/en/developers/apps/building-github-apps/refreshing-user-to-server-access-tokens

<img width="779" alt="image" src="https://user-images.githubusercontent.com/39992/134045734-12e086e2-47fd-42f2-a91f-97f6d8b2eeda.png">
