### ISSUE TITLE
When one or more 'test_matrix (XX)' Check Run fail, the 'test' Check Run is marked as 'skipped'

### ISSUE THREAD

**Issue by oscard0m** [octokit/auth-oauth-device.js#73]
This is a problem because a PR with tests failing can be merged (because the required 'test' Check Run is skipped).

---

_Originally posted by @oscard0m in https://github.com/octokit/auth-oauth-device.js/issues/45#issuecomment-1216309542_

**Comment by gr2m** [comment]
done via https://github.com/octokit/auth-oauth-device.js/pull/74
